global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: order-api
    metrics_path: /prometheus
    static_configs:
      - targets: ["order-api:8000"]

  - job_name: inventory-service
    metrics_path: /prometheus
    static_configs:
      - targets: ["inventory-service:8001"]

  - job_name: routing-engine
    metrics_path: /prometheus
    static_configs:
      - targets: ["routing-engine:8002"]

  - job_name: workflow-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["workflow-worker:9100"]
