apiVersion: v1
kind: Secret
metadata:
  name: dor-app-secrets
  namespace: __NAMESPACE__
type: Opaque
stringData:
  DATABASE_URL: "__DATABASE_URL__"
  POSTGRES_USER: "dor_admin"
  POSTGRES_PWD: "__DB_PASSWORD__"
  POSTGRES_SEEDS: "__RDS_ENDPOINT__"
  POSTGRES_DB: "order_routing"
