apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: __NAMESPACE__
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      enableServiceLinks: false
      volumes:
        - name: dynamic-config
          configMap:
            name: temporal-dynamic-config
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.25.2
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "temporal"
            - name: POSTGRES_PWD
              value: "temporal"
            - name: POSTGRES_SEEDS
              value: "temporal-postgresql"
            - name: POSTGRES_DB
              value: "temporal"
            - name: DBNAME
              value: temporal
            - name: VISIBILITY_DBNAME
              value: temporal_visibility
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/config/dynamicconfig/development-sql.yaml
            - name: TEMPORAL_ADDRESS
              value: temporal:7233
            - name: TEMPORAL_CLI_ADDRESS
              value: temporal:7233
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: dynamic-config
              mountPath: /etc/temporal/config/dynamicconfig/development-sql.yaml
              subPath: development-sql.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: __NAMESPACE__
spec:
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
